name: Build and Release Module

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip module files
        run: |
          zip -r ZRAM_Control_${{ github.ref_name }}.zip . -x "*.git*" ".github/*" "README.md"

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: ZRAM_Control_${{ github.ref_name }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}